[theme]
primaryColor = "#2ca02c"          # Цвет акцентов (благородный зеленый)
backgroundColor = "#f8f9fa"      # Светлый мягкий фон
secondaryBackgroundColor = "#ffffff" # Белоснежные карточки
textColor = "#212529"            # Темно-серый читаемый текст
font = "sans serif"              # Шрифт
